#!/bin/sh

# Configure Boxen
[ -f /opt/boxen/env.sh ] && source /opt/boxen/env.sh

# Configure homebrew
export PATH="/usr/local/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"

if [ -d "$HOME/.nodenv" ]; then
	export PATH="$HOME/.nodenv/bin:$PATH"
	eval "$(nodenv init -)"
fi

function set_java_home {
	[ -d "$1" ] && export JAVA_HOME="$1"
}

if [[ `uname | tr 'A-Z' 'a-z'` == "darwin" ]]; then
	set_java_home "/System/Library/Frameworks/JavaVM.framework/Versions/CurrentJDK/Home/"
	set_java_home "/System/Library/Frameworks/JavaVM.framework/Versions/Current/Home"
	[ -f /usr/libexec/java_home ] && export JAVA_HOME=`/usr/libexec/java_home`
fi

if [ -f `brew --prefix`/etc/bash_completion ]; then
	. `brew --prefix`/etc/bash_completion
fi
